_: {
  flake.modules.nixos.workstation =
    { lib, ... }:
    {
      nixpkgs.overlays = [
        (
          final: prev:
          let
            runtime = ./_runtime;
            themesDir = ./_themes;

            # `_`-prefixed directories are invisible to import-tree (its filter
            # is `andNot (hasInfix "/_") (hasSuffix ".nix")`), so the per-theme
            # theme.nix files stay ordinary data instead of being swept up as
            # flake-parts modules.
            themeNames = lib.attrNames (
              lib.filterAttrs (_: kind: kind == "directory") (builtins.readDir themesDir)
            );

            extensionOf = path: lib.last (lib.splitString "." (baseNameOf path));

            # The frozen browser module table dsh injects into every client
            # bundle. Nothing here is imported at runtime today — the cordis
            # import is type-only and erases — but marking them external is the
            # contract: a require() the table cannot answer is a guaranteed
            # throw at boot, so these must never be inlined.
            platformModules = [
              "react"
              "react/jsx-runtime"
              "react-dom"
              "react-dom/client"
              "@deepseek-ai/cordis"
              "@deepseek-ai/dsh-client-ui-slots"
              "@deepseek-ai/dsh-client-web-react"
              "@deepseek-ai/dsh-client-ui-primitives"
              "@deepseek-ai/dsh-client-schema-form"
            ];

            mkSkin =
              theme:
              let
                packageName = "@reclyptor/dsh-client-ui-skin-${theme.id}";
                wiringId = "ui-skin-${theme.id}";

                # Slot name drives the on-disk asset name, so a theme is free to
                # call its source files whatever it likes.
                artSlots = lib.mapAttrsToList (slot: path: {
                  inherit slot path;
                  name = "${slot}.${extensionOf path}";
                }) theme.art;

                manifest = prev.writeText "manifest.generated.ts" ''
                  /* Generated by dsh-skin.nix from _themes/${theme.id}/theme.nix. Do not edit. */
                  import type { ThemeManifest } from './manifest.ts'
                  import css from './theme.css'
                  ${lib.concatMapStringsSep "\n" (a: "import ${a.slot} from './assets/${a.name}'") artSlots}

                  export const MANIFEST: ThemeManifest = {
                    id: ${builtins.toJSON theme.id},
                    packageName: ${builtins.toJSON packageName},
                    title: ${builtins.toJSON theme.title},
                    systemChromeColor: ${builtins.toJSON theme.systemChromeColor},
                    tokens: ${builtins.toJSON theme.tokens},
                    decoration: ${builtins.toJSON (theme.decoration or { })},
                    art: { ${lib.concatMapStringsSep ", " (a: a.slot) artSlots} },
                    css,
                  }
                '';

                packageJson = (prev.formats.json { }).generate "package.json" {
                  name = packageName;
                  version = theme.version or "0.1.0";
                  inherit (theme) description;
                  private = true;
                  type = "module";
                  main = "lib/index.js";
                  exports = {
                    "." = "./lib/index.js";
                    "./client" = "./lib/client.js";
                    "./package.json" = "./package.json";
                  };
                  dsh = {
                    bundle.patch = "./cordis.patch.yml";
                    client = {
                      platform = "web";
                      # PACKAGE names, ordering the client boot graph so the
                      # theme plugin's bundle is registered before ours runs.
                      # Distinct from the SERVICE-name `inject` the runtime
                      # exports; both are needed for `ctx.theme` to resolve.
                      inject = [ "@deepseek-ai/dsh-client-ui-theme" ];
                    };
                  };
                };

                # The bundle's own patch layer: one insert row adding it to the
                # loader roster. Enabling/disabling between themes is done in a
                # higher layer by the home module.
                cordisPatch = (prev.formats.yaml { }).generate "cordis.patch.yml" [
                  {
                    insert = [
                      {
                        id = wiringId;
                        name = packageName;
                      }
                    ];
                  }
                ];

                banner = "window.__ModuleLoader__.load({ id: ${builtins.toJSON packageName}, factory: (require) => { var module = { exports: {} }; var exports = module.exports;";
              in
              prev.runCommand "dsh-skin-${theme.id}"
                {
                  nativeBuildInputs = [
                    final.esbuild
                    final.typescript
                  ];

                  passthru = {
                    inherit (theme) id;
                    inherit packageName wiringId;
                  };

                  meta = {
                    description = "dsh web skin: ${theme.description}";
                    platforms = lib.platforms.all;
                  };
                }
                ''
                  mkdir -p build/src/client/assets
                  cp -r ${runtime}/src/. build/src/
                  cp ${runtime}/tsconfig.json build/tsconfig.json
                  ${
                    if theme ? css then
                      "cp ${theme.css} build/src/client/theme.css"
                    else
                      ": > build/src/client/theme.css"
                  }
                  cp ${manifest} build/src/client/manifest.generated.ts
                  ${lib.concatMapStringsSep "\n" (a: "cp ${a.path} build/src/client/assets/${a.name}") artSlots}

                  # Typecheck against the REAL dsh type surface rather than a
                  # hand-written stub. This is the early-warning system: when a
                  # dsh bump changes the client contract, the Nix build fails
                  # loudly here instead of the skin breaking silently in the
                  # browser.
                  ln -s ${final.dsh}/lib/node_modules/@deepseek-ai/dsh/node_modules build/node_modules

                  cd build
                  tsc --noEmit

                  mkdir -p $out/lib

                  esbuild src/client/index.ts \
                    --bundle \
                    --format=cjs \
                    --platform=browser \
                    --target=es2022 \
                    --loader:.webp=dataurl \
                    --loader:.png=dataurl \
                    --loader:.svg=text \
                    --loader:.css=text \
                    ${lib.concatMapStringsSep " " (m: "--external:${m}") platformModules} \
                    --banner:js=${lib.escapeShellArg banner} \
                    --footer:js='return module.exports; } });' \
                    --outfile=$out/lib/client.js

                  esbuild src/index.ts \
                    --bundle \
                    --format=esm \
                    --platform=node \
                    --target=es2022 \
                    --external:@deepseek-ai/cordis \
                    --outfile=$out/lib/index.js

                  cp ${packageJson} $out/package.json
                  cp ${cordisPatch} $out/cordis.patch.yml
                '';
          in
          {
            # One derivation per theme directory. Adding a theme is adding a
            # directory; nothing here enumerates them by hand.
            dshSkins = lib.genAttrs themeNames (name: mkSkin (import (themesDir + "/${name}/theme.nix")));
          }
        )
      ];
    };
}
