{ config, pkgs, lib, ... }: {
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;
    systemd.enable = true;

    plugins = with pkgs.hyprlandPlugins; [
      hyprexpo
    ];

    settings = {
      # Remove autogenerated warning
      autogenerated = 0;

      # Monitor configuration - Ultrawide 5120x1440@240Hz
      monitor = [
        # Force ultrawide mode regardless of connector naming.
        ",5120x1440@240,auto,1"
      ];

      # Xwayland settings
      xwayland = {
        force_zero_scaling = true;
      };

      # Programs
      "$terminal" = "kitty";
      "$fileManager" = "nautilus";
      "$browser" = "brave";
      "$menu" = "pkill wofi || wofi --show drun";

      # Autostart applications
      exec-once = [
        "hyprpaper"
        "nm-applet --indicator"
      ];

      # Environment variables (user-level)
      env = [
        # Hyprland session identifiers
        "XDG_CURRENT_DESKTOP,Hyprland"
        "XDG_SESSION_DESKTOP,Hyprland"
        "XDG_SESSION_TYPE,wayland"
        
        # Hyprshot config
        "HYPRSHOT_DIR,/home/reclyptor/Screenshots"

        # NVIDIA + Wayland (re-enable when GPU is installed)
        # "__GLX_VENDOR_LIBRARY_NAME,nvidia"
        # "__GL_GSYNC_ALLOWED,false"
        # "__GL_VRR_ALLOWED,false"
        # "GBM_BACKEND,nvidia-drm"
      ];

      # Input configuration
      input = {
        kb_layout = "us";
        kb_variant = "";
        kb_model = "";
        kb_options = "";
        kb_rules = "";
        
        repeat_delay = 200;
        repeat_rate = 25;
        
        follow_mouse = 1;
        sensitivity = 0;
        
        touchpad = {
          natural_scroll = false;
        };
      };

      # Per-device config example
      device = {
        name = "epic-mouse-v1";
        sensitivity = -0.5;
      };

      # General window settings
      general = {
        gaps_in = 5;
        gaps_out = 20;
        border_size = 2;
        "col.active_border" = "rgba(A4C639FF)";
        "col.inactive_border" = "rgba(A4C6394D)";
        resize_on_border = false;
        allow_tearing = false;
        layout = "dwindle";
      };

      # Decoration settings
      decoration = {
        rounding = 6;
        active_opacity = 1.0;
        inactive_opacity = 1.0;
        
        shadow = {
          enabled = true;
          range = 20;
          render_power = 4;
          color = "rgba(A4C63933)";
        };
        
        blur = {
          enabled = true;
          size = 8;
          passes = 3;
          new_optimizations = true;
          xray = false;
          vibrancy = 0.2;
          vibrancy_darkness = 0.5;
        };
      };

      # Animation settings
      animations = {
        enabled = true;
        
        bezier = [
          "easeOutQuint,0.23,1,0.32,1"
          "easeInOutCubic,0.65,0.05,0.36,1"
          "linear,0,0,1,1"
          "almostLinear,0.5,0.5,0.75,1.0"
          "quick,0.15,0,0.1,1"
          "bounce,0.34,1.56,0.64,1"
        ];
        
        animation = [
          "global, 1, 10, default"
          "border, 1, 5.39, easeOutQuint"
          "windows, 1, 4.79, easeOutQuint"
          "windowsIn, 1, 5, bounce, popin 60%"
          "windowsOut, 1, 1.49, linear, popin 87%"
          "fadeIn, 1, 1.73, almostLinear"
          "fadeOut, 1, 1.46, almostLinear"
          "fade, 1, 3.03, quick"
          "layers, 1, 3.81, easeOutQuint"
          "layersIn, 1, 4, easeOutQuint, fade"
          "layersOut, 1, 1.5, linear, fade"
          "fadeLayersIn, 1, 1.79, almostLinear"
          "fadeLayersOut, 1, 1.39, almostLinear"
          "workspaces, 1, 4, easeOutQuint, slidefade 30%"
          "workspacesIn, 1, 4, easeOutQuint, slidefade 30%"
          "workspacesOut, 1, 4, easeOutQuint, slidefade 30%"
        ];
      };

      # Hyprexpo plugin settings
      plugin = {
        hyprexpo = {
          columns = 3;
          gap_size = 5;
          bg_col = "rgb(0C0F0C)";
          workspace_method = "center current";
          skip_empty = true;
          enable_gesture = false;
        };
      };

      # Layout settings
      dwindle = {
        pseudotile = true;
        preserve_split = true;
      };

      master = {
        new_status = "master";
      };

      # Misc settings
      misc = {
        force_default_wallpaper = -1;
        disable_hyprland_logo = false;
        vrr = 2;
      };

      # Key bindings
      "$mainMod" = "SUPER";

      bind = [
        # Applications
        "$mainMod, RETURN, exec, $terminal"
        "$mainMod, B, exec, $browser"
        "$mainMod, E, exec, $fileManager"
        
        # Windows
        "$mainMod, Q, killactive"
        "$mainMod SHIFT, Q, exec, hyprctl activewindow | grep pid | tr -d 'pid:' | xargs kill"
        "$mainMod, F, fullscreen, 0"
        "$mainMod, M, fullscreen, 1"
        "$mainMod, T, togglefloating"
        "$mainMod, P, pseudo"
        "$mainMod SHIFT, T, workspaceopt, allfloat"
        "$mainMod, J, togglesplit"
        "$mainMod SHIFT, l, resizeactive, 100 0"
        "$mainMod SHIFT, h, resizeactive, -100 0"
        "$mainMod SHIFT, j, resizeactive, 0 100"
        "$mainMod SHIFT, k, resizeactive, 0 -100"
        "$mainMod, G, togglegroup"
        "$mainMod, K, swapsplit"
        "CTRL ALT, h, swapwindow, l"
        "CTRL ALT, l, swapwindow, r"
        "CTRL ALT, k, swapwindow, u"
        "CTRL ALT, j, swapwindow, d"
        
        # Actions
        "$mainMod SHIFT, R, exec, hyprctl reload"
        "$mainMod SHIFT, P, exec, hyprshot -m output"
        "$mainMod SHIFT, S, exec, hyprshot -m region"
        "$mainMod CTRL, RETURN, exec, $menu"
        "$mainMod, H, exec, hyprshade toggle blue-light-filter"
        "$mainMod, L, exec, hyprlock"

        # Hyprexpo
        "CTRL, up, exec, hyprctl dispatch hyprexpo:expo toggle"
        
        # Workspaces
        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, 6, workspace, 6"
        "$mainMod, 7, workspace, 7"
        "$mainMod, 8, workspace, 8"
        "$mainMod, 9, workspace, 9"
        "$mainMod, 0, workspace, 10"
        
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod SHIFT, 6, movetoworkspace, 6"
        "$mainMod SHIFT, 7, movetoworkspace, 7"
        "$mainMod SHIFT, 8, movetoworkspace, 8"
        "$mainMod SHIFT, 9, movetoworkspace, 9"
        "$mainMod SHIFT, 0, movetoworkspace, 10"

        "$mainMod SHIFT CTRL, 1, movetoworkspacesilent, 1"
        "$mainMod SHIFT CTRL, 2, movetoworkspacesilent, 2"
        "$mainMod SHIFT CTRL, 3, movetoworkspacesilent, 3"
        "$mainMod SHIFT CTRL, 4, movetoworkspacesilent, 4"
        "$mainMod SHIFT CTRL, 5, movetoworkspacesilent, 5"
        "$mainMod SHIFT CTRL, 6, movetoworkspacesilent, 6"
        "$mainMod SHIFT CTRL, 7, movetoworkspacesilent, 7"
        "$mainMod SHIFT CTRL, 8, movetoworkspacesilent, 8"
        "$mainMod SHIFT CTRL, 9, movetoworkspacesilent, 9"
        "$mainMod SHIFT CTRL, 0, movetoworkspacesilent, 10"
        
        "$mainMod, Tab, workspace, m+1"
        "$mainMod SHIFT, Tab, workspace, m-1"
        
        "$mainMod, mouse_down, workspace, e+1"
        "$mainMod, mouse_up, workspace, e-1"
        "$mainMod CTRL, down, workspace, empty"
        
        # Move focus
        "ALT, h, movefocus, l"
        "ALT, l, movefocus, r"
        "ALT, k, movefocus, u"
        "ALT, j, movefocus, d"
      ];

      # Bind with repeat (binde)
      binde = [
        "ALT,Tab,cyclenext"
        "ALT,Tab,bringactivetotop"
      ];

      # Mouse bindings
      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];

      # Volume and brightness controls (bindel)
      bindel = [
        ",XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
        ",XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
        ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
        ",XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
        ",XF86MonBrightnessUp, exec, brightnessctl s 10%+"
        ",XF86MonBrightnessDown, exec, brightnessctl s 10%-"
      ];

      # Media controls (bindl)
      bindl = [
        ", XF86AudioNext, exec, playerctl next"
        ", XF86AudioPause, exec, playerctl play-pause"
        ", XF86AudioPlay, exec, playerctl play-pause"
        ", XF86AudioPrev, exec, playerctl previous"
      ];

      # Layer rules
      layerrule = [
        "no_anim on, match:namespace wofi"
      ];

      # Window rules
      windowrule = [
        "suppress_event maximize, match:class .*"
        "no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false"
        "float on, match:class ^(jetbrains-.*), match:title ^(win.*)"
        "no_initial_focus on, opacity 0.9 0.9, match:class ^(jetbrains-.*)"
        "opaque on, match:class ^(cursor|Cursor|code-url-handler|Code|electron)$"
        "no_blur on, match:class ^(cursor|Cursor|code-url-handler|Code|electron)$"
      ];
    };

    # Extra config for things not yet supported in settings
    extraConfig = ''
      # Additional custom configuration can go here
    '';
  };

  # Override sops-nix service environment to include age-plugin-yubikey in PATH
  systemd.user.services.sops-nix.Service.Environment = lib.mkForce "PATH=${lib.makeBinPath [ pkgs.age-plugin-yubikey ]}:/run/current-system/sw/bin";

  xdg.configFile."hypr/hyprpaper.conf".text = ''
    ipc = true
    splash = false

    wallpaper {
        monitor =
        path = /home/reclyptor/.config/wallpapers/default.jpg
        fit_mode = cover
    }
  '';

  # Copy wallpaper from Nix configuration to home directory
  home.file.".config/wallpapers/default.jpg".source = ../wallpapers/default.jpg;

  # Hypridle configuration
  services.hypridle = {
    enable = false;
    settings = {
      general = {
        lock_cmd = "pidof hyprlock || hyprlock";
        before_sleep_cmd = "loginctl lock-session";
        after_sleep_cmd = "hyprctl dispatch dpms on";
      };

      listener = [
        {
          timeout = 300; # 5 minutes - dim display
          on-timeout = "brightnessctl -s set 10";
          on-resume = "brightnessctl -r";
        }
        {
          timeout = 600; # 10 minutes - lock session
          on-timeout = "loginctl lock-session";
        }
        {
          timeout = 900; # 15 minutes - display off
          on-timeout = "hyprctl dispatch dpms off";
          on-resume = "hyprctl dispatch dpms on";
        }
      ];
    };
  };

  # Hyprlock configuration
  programs.hyprlock = {
    enable = true;
    settings = {
      general = {
        disable_loading_bar = true;
        grace = 0;
        hide_cursor = true;
        no_fade_in = false;
      };

      background = [
        {
          path = "screenshot";
          blur_passes = 3;
          blur_size = 8;
        }
      ];

      input-field = [
        {
          size = "200, 50";
          position = "0, -80";
          monitor = "";
          dots_center = true;
          fade_on_empty = false;
          font_color = "rgb(164, 198, 57)";
          inner_color = "rgb(20, 25, 20)";
          outer_color = "rgb(12, 15, 12)";
          outline_thickness = 5;
          placeholder_text = "Password...";
          shadow_passes = 2;
        }
      ];
    };
  };

  # Waybar configuration
  programs.waybar = {
    enable = true;
    systemd.enable = true;
    
    settings = {
      mainBar = {
        margin = "5 20 0 20";
        
        modules-left = [ "custom/launcher" "hyprland/workspaces" "mpris" "custom/media-shuffle" "custom/media-prev" "custom/media-play" "custom/media-next" "custom/media-loop" ];
        modules-center = [ "clock" ];
        modules-right = [ "bluetooth" "network" "cpu" "memory" "temperature" "disk" "pulseaudio" "tray" ];

        "custom/launcher" = {
          format = "  ";
          interval = 7200;
          on-click = "pkill wofi || wofi --show drun";
          signal = 8;
        };

        "hyprland/workspaces" = {
          format = "{icon}";
          format-icons = {
            active = "󰮯";
            default = "󰊠";
            empty = "󰝦";
          };
          persistent-workspaces = {
            "*" = 5;
          };
        };

        mpris = {
          format = "{player_icon} {dynamic}";
          format-paused = "{status_icon} {dynamic}";
          interval = 1;
          player-icons = {
            default = "󰎇";
            spotify = "󰓇";
            mpv = "󰐹";
            firefox = "󰈹";
          };
          status-icons = {
            paused = "󰏤";
          };
          max-length = 60;
        };

        "custom/media-prev" = {
          format = "󰒮";
          on-click = "playerctl previous";
          tooltip = false;
        };

        "custom/media-play" = {
          format = "{}";
          return-type = "json";
          exec = "bash -lc 'state=$(playerctl status 2>/dev/null || echo Stopped); case \"$state\" in Playing) echo \"{\\\"text\\\":\\\"󰏤\\\"}\" ;; Paused) echo \"{\\\"text\\\":\\\"󰐊\\\"}\" ;; *) echo \"{\\\"text\\\":\\\"󰐊\\\",\\\"class\\\":\\\"off\\\"}\" ;; esac'";
          on-click = "playerctl play-pause";
          interval = 1;
          tooltip = false;
        };

        "custom/media-next" = {
          format = "󰒭";
          on-click = "playerctl next";
          tooltip = false;
        };

        "custom/media-shuffle" = {
          format = "{}";
          return-type = "json";
          exec = "bash -lc 'state=$(playerctl shuffle 2>/dev/null || echo Off); if [ \"$state\" = \"On\" ]; then echo \"{\\\"text\\\":\\\"󰒟\\\"}\"; else echo \"{\\\"text\\\":\\\"\\\",\\\"class\\\":\\\"off\\\"}\"; fi'";
          on-click = "playerctl shuffle toggle";
          interval = 1;
          tooltip = false;
        };

        "custom/media-loop" = {
          format = "{}";
          return-type = "json";
          exec = "bash -lc 'state=$(playerctl loop 2>/dev/null || echo None); case \"$state\" in None) echo \"{\\\"text\\\":\\\"󰑖\\\",\\\"class\\\":\\\"none\\\"}\" ;; Track) echo \"{\\\"text\\\":\\\"󰑘\\\"}\" ;; Playlist) echo \"{\\\"text\\\":\\\"󰑖\\\"}\" ;; *) echo \"{\\\"text\\\":\\\"󰑖\\\",\\\"class\\\":\\\"none\\\"}\" ;; esac'";
          on-click = "bash -lc 'state=$(playerctl loop 2>/dev/null || echo None); case \"$state\" in None) playerctl loop Playlist ;; Playlist) playerctl loop Track ;; Track) playerctl loop None ;; *) playerctl loop None ;; esac'";
          interval = 1;
          tooltip = false;
        };

        cpu = {
          format = "  {usage}%";
          interval = 2;
          on-click = "kitty --class btop -e btop";
        };

        memory = {
          format = "  {percentage}%";
          interval = 2;
        };

        temperature = {
          critical-threshold = 85;
          format = "{icon} {temperatureC}°C";
          format-icons = [ "" "" "" ];
        };

        disk = {
          interval = 30;
          format = "󰋊 {percentage_used}%";
          path = "/";
          tooltip-format = "{path}: {used}/{total} ({percentage_used}%)";
        };

        bluetooth = {
          format = " {status}";
          format-connected = " {device_alias}";
          format-connected-battery = " {device_alias} {device_battery_percentage}%";
          tooltip-format = "{controller_alias}\t{controller_address}";
          tooltip-format-connected = "{controller_alias}\t{controller_address}\n{num_connections} connected";
          on-click = "blueman-manager";
        };

        clock = {
          tooltip-format = "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>";
          format = "{:%A | %d %b %Y | %H:%M:%S}";
          interval = 1;
        };

        network = {
          format-wifi = "󰖩  {essid} ({signalStrength}%)";
          format-ethernet = "󰈀 Ethernet";
          format-disconnected = "󰖪 Disconnected";
          on-click = "nm-connection-editor";
        };

        pulseaudio = {
          reverse-scrolling = 1;
          format = "{volume}% {icon}";
          format-bluetooth = "{volume}% {icon}";
          format-muted = " {format_source}";
          format-source-muted = "Muted 🚫";
          format-icons = {
            headphone = "🎧";
            default = [ "🔈" "🔉" "🔊" ];
          };
          on-click = "pavucontrol";
          min-length = 13;
        };

        tray = {
          icon-size = 16;
          spacing = 4;
        };
      };
    };

    style = ''
      * {
        border: none;
        border-radius: 0;
        font-family: JetBrainsMono Nerd Font, monospace;
        font-size: 14px;
        min-height: 0px;
      }

      window#waybar {
        background: transparent;
      }

      window#waybar.hidden {
        opacity: 0.2;
      }

      #custom-launcher {
        padding-left: 10px;
        padding-right: 10px;
        border-radius: 5px 20px 5px 20px;
        border: solid 2px;
        border-color: #A4C639;
        transition: background 0.3s ease,
        border-radius 0.3s ease;
        background: #141914;
        color: #A4C639;
      }

      #custom-launcher:hover {
        border-radius: 20px 5px 20px 5px;
        background: #A4C639;
        color: #141914;
      }

      #workspaces {
        margin-left: 8px;
      }

      #workspaces button {
        padding: 0 8px;
        border-radius: 5px 20px 5px 20px;
        border: solid 2px #A4C639;
        background: #141914;
        color: #A4C639;
        transition: all 0.3s ease;
        margin-right: 4px;
      }

      #workspaces button:hover {
        border-radius: 20px 5px 20px 5px;
        background: rgba(164, 198, 57, 0.2);
      }

      #workspaces button.active {
        border-radius: 20px 5px 20px 5px;
        background: #A4C639;
        color: #141914;
        font-weight: bold;
      }

      #workspaces button.empty {
        opacity: 0.4;
      }

      #mpris,
      #custom-media-shuffle,
      #custom-media-prev,
      #custom-media-play,
      #custom-media-next,
      #custom-media-loop {
        margin-left: 8px;
        padding-left: 12px;
        padding-right: 12px;
        border-radius: 5px 20px 5px 20px;
        border: solid 2px;
        border-color: #A4C639;
        transition: background 0.3s ease-in-out,
        border-radius 0.3s ease-in-out;
        background: #141914;
        color: #A4C639;
      }

      #custom-media-shuffle,
      #custom-media-prev,
      #custom-media-play,
      #custom-media-next,
      #custom-media-loop {
        min-width: 28px;
      }

      #custom-media-shuffle.off {
        color: #6b7450;
        border-color: #6b7450;
      }

      #custom-media-play.off {
        color: #6b7450;
        border-color: #6b7450;
      }

      #custom-media-loop.none {
        color: #6b7450;
        border-color: #6b7450;
      }

      #mpris:hover,
      #custom-media-shuffle:hover,
      #custom-media-prev:hover,
      #custom-media-play:hover,
      #custom-media-next:hover,
      #custom-media-loop:hover {
        border-radius: 20px 5px 20px 5px;
        background: #A4C639;
        color: #141914;
      }

      #cpu,
      #memory,
      #temperature,
      #disk,
      #bluetooth {
        margin-right: 8px;
        padding-left: 10px;
        padding-right: 10px;
        border-radius: 20px 5px 20px 5px;
        border: solid 2px;
        border-color: #A4C639;
        transition: background 0.3s ease-in-out,
        border-radius 0.3s ease-in-out;
        background: #141914;
        color: #A4C639;
      }

      #cpu:hover,
      #memory:hover,
      #temperature:hover,
      #disk:hover,
      #bluetooth:hover {
        border-radius: 5px 20px 5px 20px;
        background: #A4C639;
        color: #141914;
      }

      #clock {
        padding-left: 16px;
        padding-right: 16px;
        border-radius: 5px 5px 20px 20px;
        border: solid 2px;
        border-color: #A4C639;
        transition: background 0.3s ease,
        border-radius 0.3s ease;
        background: #141914;
        color: #A4C639;
      }

      #clock:hover {
        border-radius: 20px 20px 5px 5px;
        background: #A4C639;
        color: #141914;
      }

      #network {
        margin-right: 8px;
        padding-right: 15px;
        padding-left: 15px;
        border-radius: 20px 5px 20px 5px;
        border: solid 2px;
        border-color: #A4C639;
        transition: background 0.3s ease,
        border-radius 0.3s ease;
        background: #141914;
        color: #A4C639;
      }

      #network:hover {
        border-radius: 5px 20px 5px 20px;
        background: #A4C639;
        color: #141914;
      }

      #pulseaudio {
        margin-right: 8px;
        border-radius: 20px 5px 20px 5px;
        padding-left: 0px;
        padding-right: 0px;
        border: solid 2px;
        border-color: #A4C639;
        transition: background 0.3s ease,
        border-radius 0.3s ease;
        background: #141914;
        color: #A4C639;
      }

      #pulseaudio:hover {
        border-radius: 5px 20px 5px 20px;
        background: #A4C639;
        color: #141914;
      }

      #tooltip {
        background: #141914;
        color: #A4C639;
      }

      #tray {
        padding-left: 16px;
        padding-right: 16px;
        border-radius: 20px 5px 20px 5px;
        border: solid 2px;
        border-color: #A4C639;
        transition: background 0.3s ease,
        border-radius 0.3s ease;
        background: #141914;
        color: #A4C639;
      }

      #tray:hover {
        border-radius: 5px 20px 5px 20px;
        background: #A4C639;
        color: #141914;
      }

      @keyframes blink {
        to {
          background-color: #ffffff;
          color: #484a4a;
        }
      }
    '';
  };


  # Mako notification daemon
  services.mako = {
    enable = true;
    settings = {
      anchor = "top-center";
      default-timeout = 5000;
      background-color = "#0C0F0C";
      text-color = "#A4C639";
      border-color = "#A4C639";
      border-radius = 10;
      border-size = 2;
      width = 300;
      height = 100;
      padding = "10";
      margin = "10";
    };
  };

  # Wofi launcher
  programs.wofi = {
    enable = true;
    settings = {
      hide_scroll = true;
      show = "drun";
      width = "30%";
      height = 460;
      lines = 8;
      line_wrap = "word";
      term = "kitty";
      allow_markup = true;
      always_parse_args = false;
      show_all = true;
      print_command = true;
      layer = "overlay";
      allow_images = false;
      sort_order = "alphabetical";
      gtk_dark = true;
      prompt = "";
      image_size = 20;
      display_generic = false;
      location = "center";
      key_expand = "Tab";
      insensitive = false;
    };
    
    style = ''
      window {
        border: 2px solid #A4C639;
        background-color: #0C0F0C;
        border-radius: 8px;
        opacity: 1.0;
        height: 460px;
        min-height: 460px;
        max-height: 460px;
      }

      #input {
        margin: 5px;
        border: #A4C639;
        color: #A4C639;
        background-color: #0C0F0C;
      }

      #inner-box {
        margin: 8px;
        border: none;
        background-color: #0C0F0C;
        min-height: 0;
      }

      #outer-box {
        margin: 8px;
        border: none;
        background-color: #0C0F0C;
        min-height: 0;
      }

      #scroll {
        margin: 0px;
        border: none;
        background-color: #0C0F0C;
        overflow: auto;
        min-height: 0;
      }

      #text {
        margin: 5px;
        border: none;
        color: #A4C639;
      } 

      #entry.activatable #text {
        color: #282a36;
      }

      #entry > * {
        color: #A4C639;
      }

      #entry:selected {
        background-color: #A4C639;
        border-radius: 6px;
      }

      #entry:selected #text {
        background-color: #;
        color: #0C0F0C;
        font-weight: bold;
      }
    '';
  };


  # Create screenshots directory
  home.file."Screenshots/.keep".text = "";
}