# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "sg" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "rpool/nixos/root";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "rpool/nixos/home";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "rpool/nixos/nix";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/19B9-12B7";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/a728d073-021a-4b0b-8529-47acf09e7ee2"; }
  ];

  fileSystems."/data/nvme" = {
    device = "npool/data";
    fsType = "zfs";
  };

  fileSystems."/data/nvme/steam" = {
    device = "npool/data/steam";
    fsType = "zfs";
  };

  fileSystems."/data/ssd" = {
    device = "spool/data";
    fsType = "zfs";
  };

  fileSystems."/data/nfs/dxp6800" = {
    device = "192.168.1.2:/mnt/primary/videos";
    fsType = "nfs4";
    options = [ "defaults" "_netdev" "x-systemd.automount" ];
  };

  fileSystems."/data/nfs/dxp4800" = {
    device = "192.168.1.3:/mnt/primary/videos";
    fsType = "nfs4";
    options = [ "defaults" "_netdev" "x-systemd.automount" ];
  };

  fileSystems."/data/nfs/flashstor/videos" = {
    device = "192.168.1.4:/mnt/primary/videos";
    fsType = "nfs4";
    options = [ "defaults" "_netdev" "x-systemd.automount" ];
  };

  fileSystems."/data/nfs/flashstor/data" = {
    device = "192.168.1.4:/mnt/primary/data";
    fsType = "nfs4";
    options = [ "defaults" "_netdev" "x-systemd.automount" ];
  };

  fileSystems."/data/nfs/asustor" = {
    device = "192.168.1.6:/volume1/data";
    fsType = "nfs4";
    options = [ "defaults" "_netdev" "x-systemd.automount" ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
