{ inputs, ... }: {
  # Formatting and lint gate. Gives `nix fmt` to format the tree and a
  # `checks.<system>.treefmt` that `nix flake check` runs alongside its own
  # evaluation of every nixosConfiguration — so a bad file fails CI-style
  # instead of being noticed months later.
  imports = [ inputs.treefmt-nix.flakeModule ];

  perSystem = { ... }: {
    treefmt = {
      projectRootFile = "flake.nix";

      programs.nixfmt.enable = true;   # formatting (RFC 166 style)
      programs.deadnix.enable = true;  # unused bindings / dead code
      programs.statix.enable = true;   # anti-patterns and redundant constructs

      settings.global.excludes = [
        # Generated by nixos-generate-config and carrying its "do not modify"
        # header. statix flags the repeated `fileSystems."/…"` keys in these,
        # but rewriting them would create diff noise the next time the
        # generator runs over a host.
        "hardware/*.nix"
        # Not ours to format.
        "*.json"
        "*.lock"
        "*.jpg"
        "*.yaml"
      ];
    };
  };
}
