{ ... }: {
  flake.modules.homeManager.base = { config, ... }: let palette = config.palette; in {
    wayland.windowManager.hyprland = {
      enable = true;
      xwayland.enable = true;
      systemd.enable = true;
      # settings below are hyprlang; pin the format (default flips to lua at stateVersion 26.05).
      configType = "hyprlang";

      settings = {
        # Remove autogenerated warning
        autogenerated = 0;

        # Monitor configuration - Ultrawide 5120x1440@240Hz
        monitor = [
          # Force ultrawide mode regardless of connector naming.
          ",5120x1440@240,auto,1"
        ];

        # Xwayland settings
        xwayland = {
          force_zero_scaling = true;
        };

        # Programs
        "$terminal" = "kitty";
        "$fileManager" = "nautilus";
        "$browser" = "brave";
        "$menu" = "pkill fuzzel || fuzzel";

        # Autostart applications
        exec-once = [
          "gnome-keyring-daemon --start --components=secrets,pkcs11"
          "hyprpaper"
          "nm-applet --indicator"
        ];

        # Environment variables (user-level)
        env = [
          # Hyprland session identifiers
          "XDG_CURRENT_DESKTOP,Hyprland"
          "XDG_SESSION_DESKTOP,Hyprland"
          "XDG_SESSION_TYPE,wayland"
          
          # Hyprshot config
          "HYPRSHOT_DIR,${config.home.homeDirectory}/Screenshots"
        ];

        # Input configuration
        input = {
          kb_layout = "us";
          kb_variant = "";
          kb_model = "";
          kb_options = "";
          kb_rules = "";
          
          repeat_delay = 200;
          repeat_rate = 25;
          
          follow_mouse = 1;
          sensitivity = 0;
          
          touchpad = {
            natural_scroll = false;
          };
        };

        # Per-device config example
        device = {
          name = "epic-mouse-v1";
          sensitivity = -0.5;
        };

        # General window settings
        general = {
          gaps_in = 5;
          gaps_out = 20;
          border_size = 2;
          "col.active_border" = "rgba(${palette.accent}FF)";
          "col.inactive_border" = "rgba(${palette.accent}4D)";
          resize_on_border = false;
          allow_tearing = false;
          layout = "dwindle";
        };

        # Decoration settings
        decoration = {
          rounding = 6;
          active_opacity = 1.0;
          inactive_opacity = 1.0;
          
          shadow = {
            enabled = true;
            range = 20;
            render_power = 4;
            color = "rgba(${palette.accent}33)";
          };
          
          blur = {
            enabled = true;
            size = 8;
            passes = 3;
            new_optimizations = true;
            xray = false;
            vibrancy = 0.2;
            vibrancy_darkness = 0.5;
          };
        };

        # Animation settings
        animations = {
          enabled = true;
          
          bezier = [
            "easeOutQuint,0.23,1,0.32,1"
            "easeInOutCubic,0.65,0.05,0.36,1"
            "linear,0,0,1,1"
            "almostLinear,0.5,0.5,0.75,1.0"
            "quick,0.15,0,0.1,1"
            "bounce,0.34,1.56,0.64,1"
          ];
          
          animation = [
            "global, 1, 10, default"
            "border, 1, 5.39, easeOutQuint"
            "windows, 1, 4.79, easeOutQuint"
            "windowsIn, 1, 5, bounce, popin 60%"
            "windowsOut, 1, 1.49, linear, popin 87%"
            "fadeIn, 1, 1.73, almostLinear"
            "fadeOut, 1, 1.46, almostLinear"
            "fade, 1, 3.03, quick"
            "layers, 1, 3.81, easeOutQuint"
            "layersIn, 1, 4, easeOutQuint, fade"
            "layersOut, 1, 1.5, linear, fade"
            "fadeLayersIn, 1, 1.79, almostLinear"
            "fadeLayersOut, 1, 1.39, almostLinear"
            "workspaces, 1, 4, easeOutQuint, slidefade 30%"
            "workspacesIn, 1, 4, easeOutQuint, slidefade 30%"
            "workspacesOut, 1, 4, easeOutQuint, slidefade 30%"
          ];
        };

        # Layout settings
        dwindle = {
          preserve_split = true;
        };

        master = {
          new_status = "master";
        };

        # Misc settings
        misc = {
          force_default_wallpaper = -1;
          disable_hyprland_logo = false;
          vrr = 2;
        };

        ecosystem = {
          no_update_news = true;
        };

        # Key bindings
        "$mainMod" = "SUPER";

        bind = [
          # Applications
          "$mainMod, RETURN, exec, $terminal"
          "$mainMod, B, exec, $browser"
          "$mainMod, E, exec, $fileManager"
          
          # Windows
          "$mainMod, Q, killactive"
          "$mainMod SHIFT, Q, exec, hyprctl activewindow | grep pid | tr -d 'pid:' | xargs kill"
          "$mainMod, F, fullscreen, 0"
          "$mainMod, M, fullscreen, 1"
          "$mainMod, T, togglefloating"
          "$mainMod ALT, P, pin"
          "$mainMod, P, pseudo"
          "$mainMod SHIFT, T, layoutmsg, allfloat"
          "$mainMod, J, layoutmsg, togglesplit"
          "$mainMod SHIFT, l, resizeactive, 100 0"
          "$mainMod SHIFT, h, resizeactive, -100 0"
          "$mainMod SHIFT, j, resizeactive, 0 100"
          "$mainMod SHIFT, k, resizeactive, 0 -100"
          "$mainMod, G, togglegroup"
          "$mainMod SHIFT, G, moveoutofgroup"
          "$mainMod, K, layoutmsg, swapsplit"
          "$mainMod CTRL, h, swapwindow, l"
          "$mainMod CTRL, l, swapwindow, r"
          "$mainMod CTRL, k, swapwindow, u"
          "$mainMod CTRL, j, swapwindow, d"
          
          # Actions
          "$mainMod SHIFT, R, exec, hyprctl reload"
          "$mainMod SHIFT, P, exec, hyprshot -m output"
          "$mainMod SHIFT, S, exec, hyprshot -m region"
          "$mainMod CTRL, RETURN, exec, $menu"
          "$mainMod, H, exec, hyprshade toggle blue-light-filter"
          "$mainMod, L, exec, hyprlock"

          # Workspaces
          "$mainMod, 1, workspace, 1"
          "$mainMod, 2, workspace, 2"
          "$mainMod, 3, workspace, 3"
          "$mainMod, 4, workspace, 4"
          "$mainMod, 5, workspace, 5"
          "$mainMod, 6, workspace, 6"
          "$mainMod, 7, workspace, 7"
          "$mainMod, 8, workspace, 8"
          "$mainMod, 9, workspace, 9"
          "$mainMod, 0, workspace, 10"
          
          "$mainMod SHIFT, 1, movetoworkspace, 1"
          "$mainMod SHIFT, 2, movetoworkspace, 2"
          "$mainMod SHIFT, 3, movetoworkspace, 3"
          "$mainMod SHIFT, 4, movetoworkspace, 4"
          "$mainMod SHIFT, 5, movetoworkspace, 5"
          "$mainMod SHIFT, 6, movetoworkspace, 6"
          "$mainMod SHIFT, 7, movetoworkspace, 7"
          "$mainMod SHIFT, 8, movetoworkspace, 8"
          "$mainMod SHIFT, 9, movetoworkspace, 9"
          "$mainMod SHIFT, 0, movetoworkspace, 10"

          "$mainMod SHIFT CTRL, 1, movetoworkspacesilent, 1"
          "$mainMod SHIFT CTRL, 2, movetoworkspacesilent, 2"
          "$mainMod SHIFT CTRL, 3, movetoworkspacesilent, 3"
          "$mainMod SHIFT CTRL, 4, movetoworkspacesilent, 4"
          "$mainMod SHIFT CTRL, 5, movetoworkspacesilent, 5"
          "$mainMod SHIFT CTRL, 6, movetoworkspacesilent, 6"
          "$mainMod SHIFT CTRL, 7, movetoworkspacesilent, 7"
          "$mainMod SHIFT CTRL, 8, movetoworkspacesilent, 8"
          "$mainMod SHIFT CTRL, 9, movetoworkspacesilent, 9"
          "$mainMod SHIFT CTRL, 0, movetoworkspacesilent, 10"
          
          "$mainMod, Tab, workspace, m+1"
          "$mainMod SHIFT, Tab, workspace, m-1"
          
          "$mainMod, mouse_down, workspace, e+1"
          "$mainMod, mouse_up, workspace, e-1"
          "$mainMod, down, workspace, empty"
          
          # Move focus
          "ALT, h, movefocus, l"
          "ALT, l, movefocus, r"
          "ALT, k, movefocus, u"
          "ALT, j, movefocus, d"
        ];

        # Bind with repeat (binde)
        binde = [
          "ALT,Tab,cyclenext"
          "ALT,Tab,alterzorder, top"
        ];

        # Mouse bindings
        bindm = [
          "$mainMod, mouse:272, movewindow"
          "$mainMod, mouse:273, resizewindow"
        ];

        # Volume and brightness controls (bindel)
        bindel = [
          ",XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
          ",XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
          ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
          ",XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
          ",XF86MonBrightnessUp, exec, brightnessctl s 10%+"
          ",XF86MonBrightnessDown, exec, brightnessctl s 10%-"
        ];

        # Media controls (bindl)
        bindl = [
          ", XF86AudioNext, exec, playerctl next"
          ", XF86AudioPause, exec, playerctl play-pause"
          ", XF86AudioPlay, exec, playerctl play-pause"
          ", XF86AudioPrev, exec, playerctl previous"
        ];

        # Layer rules
        layerrule = [
          "no_anim on, match:namespace launcher"
        ];

        # Window rules
        windowrule = [
          "suppress_event maximize, match:class .*"
          "no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false"
          "float on, match:class ^(jetbrains-.*), match:title ^(win.*)"
          "no_initial_focus on, opacity 0.9 0.9, match:class ^(jetbrains-.*)"
          "opaque on, match:class ^(cursor|Cursor|code-url-handler|Code|electron)$"
          "no_blur on, match:class ^(cursor|Cursor|code-url-handler|Code|electron)$"
        ];
      };
    };

    # Create screenshots directory
    home.file."Screenshots/.keep".text = "";
  };
}
